spring.application.name=demo

# PostgreSQL bağlantısı
spring.datasource.url=jdbc:postgresql://demo-postgres:5432/demo_db
spring.datasource.username=demo_user
spring.datasource.password=demo_password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info